### ISSUE TITLE
Energy Usage virtual devices

### ISSUE THREAD

**Issue by sOckhamSter** [verbem/Domoticz-Server#4] opened 2019-01-19 20:27 UTC
I've added support for creating virtual power meters in Domoticz from devices supporting a power meter in SmartThings. This functionality has been merged into the master repo but I can only figure out how to get the power usage from the devices, not energy usage. I have left a placeholder for the energy usage value to be submitted:

`socketSend([request: "SetPower", idx: idx, power:evt.stringValue, energy:"0"])
`
See that 0 in quotes? That's where it should go. Does anyone have any ideas how we can get the energy usage from devices at the same time as the power usage? The SmartThings devices I'm testing with are Fibaro Dimmer 2 and Aeotec Micro Smart Switch. It would be good to add the energy usage for the sake of completeness.

**Comment by verbem** [comment] 2019-01-19 20:41
I will take a look at it..


Verzonden vanaf Samsung-tablet.
-------- Oorspronkelijk bericht --------Van: sOckhamSter <notifications@github.com> Datum: 19-01-19  21:27  (GMT+01:00) Aan: verbem/Domoticz-Server <Domoticz-Server@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Onderwerp: [verbem/Domoticz-Server] Energy Usage virtual devices (#4) 
I've added support for creating virtual power meters in Domoticz from devices supporting a power meter in SmartThings. This functionality has been merged into the master repo but I can only figure out how to get the power usage from the devices, not energy usage. I have left a placeholder for the energy usage value to be submitted:
socketSend([request: "SetPower", idx: idx, power:evt.stringValue, energy:"0"]) 

See that 0 in quotes? That's where it should go. Does anyone have any ideas how we can get the energy usage from devices at the same time as the power usage? The SmartThings devices I'm testing with are Fibaro Dimmer 2 and Aeotec Micro Smart Switch. It would be good to add the energy usage for the sake of completeness.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/verbem/Domoticz-Server","title":"verbem/Domoticz-Server","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/verbem/Domoticz-Server"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Energy Usage virtual devices (#4)"}],"action":{"name":"View Issue","url":"https://github.com/verbem/Domoticz-Server/issues/4"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/verbem/Domoticz-Server/issues/4",
"url": "https://github.com/verbem/Domoticz-Server/issues/4",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by verbem** [comment] 2019-01-20 11:15
Could you send me a screenshot of both the devices in the IDE where it shows the attribute states?


________________________________
Van: sOckhamSter <notifications@github.com>
Verzonden: Saturday, January 19, 2019 9:27:57 PM
Aan: verbem/Domoticz-Server
CC: Subscribed
Onderwerp: [verbem/Domoticz-Server] Energy Usage virtual devices (#4)


I've added support for creating virtual power meters in Domoticz from devices supporting a power meter in SmartThings. This functionality has been merged into the master repo but I can only figure out how to get the power usage from the devices, not energy usage. I have left a placeholder for the energy usage value to be submitted:

socketSend([request: "SetPower", idx: idx, power:evt.stringValue, energy:"0"])
See that 0 in quotes? That's where it should go. Does anyone have any ideas how we can get the energy usage from devices at the same time as the power usage? The SmartThings devices I'm testing with are Fibaro Dimmer 2 and Aeotec Micro Smart Switch. It would be good to add the energy usage for the sake of completeness.

**Comment by verbem** [comment] 2019-01-20 11:38
Try version 7.23 , i do not have native connected smartthings devices that support energyMeter, but i have added some code to get this value when power is udated. If the devices use energyMeter capability it should work. But cannot test it.

________________________________
Van: sOckhamSter <notifications@github.com>
Verzonden: Saturday, January 19, 2019 9:27:57 PM
Aan: verbem/Domoticz-Server
CC: Subscribed
Onderwerp: [verbem/Domoticz-Server] Energy Usage virtual devices (#4)


I've added support for creating virtual power meters in Domoticz from devices supporting a power meter in SmartThings. This functionality has been merged into the master repo but I can only figure out how to get the power usage from the devices, not energy usage. I have left a placeholder for the energy usage value to be submitted:

socketSend([request: "SetPower", idx: idx, power:evt.stringValue, energy:"0"])
See that 0 in quotes? That's where it should go. Does anyone have any ideas how we can get the energy usage from devices at the same time as the power usage? The SmartThings devices I'm testing with are Fibaro Dimmer 2 and Aeotec Micro Smart Switch. It would be good to add the energy usage for the sake of completeness.

**Comment by sOckhamSter** [comment] 2019-01-20 19:18
<img width="465" alt="aeotec" src="https://user-images.githubusercontent.com/4546972/51443882-aef7a880-1ce7-11e9-9189-9365a4511ff2.png">
<img width="465" alt="fibaro" src="https://user-images.githubusercontent.com/4546972/51443883-b323c600-1ce7-11e9-8358-03f14716a994.png">

Here are the attributes for the aeotec and the fibaro. 7.23 doesn't appear to send the energy usage, it just sets usage to 0. But I've discovered a workaround. I can set the device in Domoticz to 'Computed' for energy read.

<img width="572" alt="energy in domoticz" src="https://user-images.githubusercontent.com/4546972/51443906-29282d00-1ce8-11e9-8ff8-2151131f299f.png">

**Comment by verbem** [comment] 2019-01-20 20:53
I see what the issue is, will update to 7.25 shortly this will get the right value. 0 is used as it does not find the attribute.

**Comment by verbem** [comment] 2019-01-21 16:00
7.25 has been committed, it tests for existence of both energy or energyMeter as a value on the device and pushes this to Domoticz

**Comment by sOckhamSter** [comment] 2019-01-23 09:14
I left it running for just over 24 hours in case they were slow reporting devices but no energy consumption was reported to Domoticz. For now I'm happy with the Domoticz workaround calculating that for me but if I get chance I'll try and dig in to the code and see if I can figure out what's happening with my devices. You can never have too many TRACE statements...

**Comment by verbem** [comment] 2019-01-23 09:18
I have found a way to get a device defined in SmartThing to test energy attribute, it should work this way. Will be back soon.

________________________________

**Comment by verbem** [comment] 2019-01-24 08:49
Just committed 7.26. Eventhandling was missing for energy and energymeters, also the logic for setting correct virtualdevicetype was changed.


________________________________
Van: sOckhamSter <notifications@github.com>
Verzonden: Wednesday, January 23, 2019 10:14:03 AM
Aan: verbem/Domoticz-Server
CC: Martin Verbeek; Comment
Onderwerp: Re: [verbem/Domoticz-Server] Energy Usage virtual devices (#4)


I left it running for just over 24 hours in case they were slow reporting devices but no energy consumption was reported to Domoticz. For now I'm happy with the Domoticz workaround calculating that for me but if I get chance I'll try and dig in to the code and see if I can figure out what's happening with my devices. You can never have too many TRACE statements...

**Comment by sOckhamSter** [comment] 2019-01-24 09:05
I've updated and will run it for a day then let you know how it goes...

**Comment by verbem** [comment] 2019-01-24 19:54
Thx, make sure you press save in the app once to have the new events handled...

Op do 24 jan. 2019 10:05 schreef sOckhamSter <notifications@github.com<mailto:notifications@github.com>:

I've updated and will run it for a day then let you know how it goes...

**Comment by sOckhamSter** [comment] 2019-01-29 20:07
Well it appears to be picking something up for energy usage now so thank you. It's a little erratic in its delivery but I think that's down to when the modules send their reports. Each day is showing about the expected usage so all is good I think! Thanks for your help.

**Comment by verbem** [comment] 2019-01-29 20:16
Could you check in domoticz the update interval dit sensors in the settings? Default it can be high.

Op di 29 jan. 2019 21:07 schreef sOckhamSter <notifications@github.com<mailto:notifications@github.com>:

Well it appears to be picking something up for energy usage now so thank you. It's a little erratic in its delivery but I think that's down to when the modules send their reports. Each day is showing about the expected usage so all is good I think! Thanks for your help.

**Closed as completed** 2020-05-15 19:48 UTC
